# -*- coding: utf-8 -*-
from django.conf.urls import url

import samraemd.views as s

app_name = 'samraemd'
urlpatterns = [
    url(r'^niðurstöður/(?P<school_id>\d+)$',
        s.SamraemdResultListing.as_view(),
        name='result_list'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)$',
        s.SamraemdResultDetail.as_view(),
        name='result_detail'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)/hrágögn/$',
        s.SamraemdRawResultDetail.as_view(),
        name='result_detail_raw'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)/hrágögn/einkunnablod/$',
        s.SamraemdRawResultDetail.as_view(),
        name='result_raw_print'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)/einkunnablod/$',
        s.SamraemdResultDetail.as_view(),
        name='result_print'),
    url(r'^niðurstöður/(?P<year>\d+)/(?P<group>\d+)/einkunnablod/$',
        s.SamraemdResultDetail.as_view(),
        name='admin_result_print'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)/excel/$',
        s.excel_result,
        name='result_excel'),
    url(r'^niðurstöður/(?P<school_id>\d+)/(?P<year>\d+)/(?P<group>\d+)/hrá/excel/$',
        s.excel_result_raw,
        name='result_raw_excel'),

    url(r'^stæ/$',
        s.SamraemdMathResultAdminListing.as_view(),
        name='math_admin_listing'),
    url(r'^stæ/(?P<school_id>\d+)/$',
        s.SamraemdMathResultListing.as_view(),
        name='math_listing'),
    url(r'^stæ/niðurstöður/create/$',
        s.SamraemdMathResultCreate.as_view(),
        name='math_create'),
    url(r'^stæ/niðurstöður/(?P<exam_code>[\w ]+)/delete/$',
        s.SamraemdMathResultDelete.as_view(),
        name='math_delete'),
    url(r'^isl/$',
        s.SamraemdISLResultAdminListing.as_view(),
        name='isl_admin_listing'),
    url(r'^isl/(?P<school_id>\d+)/$',
        s.SamraemdISLResultListing.as_view(),
        name='isl_listing'),
    url(r'^isl/niðurstöður/create/$',
        s.SamraemdISLResultCreate.as_view(),
        name='isl_create'),
    url(r'^niðurstöður/rawdata/$',
        s.RawDataCreate.as_view(),
        name='rawdatacreate'),
    url(r'^isl/niðurstöður/(?P<exam_code>[\w ]+)/delete/$',
        s.SamraemdISLResultDelete.as_view(),
        name='isl_delete'),
    url(r'^niðurstöður/(?P<exam_code>[\w ]+)/(?P<year>\d+)/(?P<group>\d+)/delete/$',
        s.SamraemdResultDelete.as_view(),
        name='raw_delete'),
    url(r'^umsjónarmaður/stæ/niðurstöður/(?P<year>\d+)/(?P<group>\d+)$',
        s.SamraemdResultDetail.as_view(),
        name='math_admin_result_detail'),
    url(r'^umsjónarmaður/isl/niðurstöður/(?P<year>\d+)/(?P<group>\d+)$',
        s.SamraemdResultDetail.as_view(),
        name='isl_admin_result_detail'),
    url(r'^umsjónarmaður/niðurstöður/(?P<exam_code>\w+)/(?P<year>\d+)/(?P<group>\d+)$',
        s.SamraemdRawResultDetail.as_view(),
        name='admin_result_detail'),
    url(r'^umsjónarmaður/niðurstöður/(?P<exam_code>\w+)/(?P<year>\d+)/(?P<group>\d+)/rawexcel/$',
        s.admin_result_raw_excel,
        name='admin_result_raw_excel'),
    url(r'^umsjónarmaður/niðurstöður/(?P<exam_code>\w+)/(?P<year>\d+)/(?P<group>\d+)/einkunnablod/$',
        s.SamraemdRawResultDetail.as_view(),
        name='admin_result_raw_print'),
]
