language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.5"
# command to run tests
script: make travis-test
