language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - pip install six
# command to install dependencies
install:
  - pip install -r requirements.txt
services:
  - postgresql
# command to run tests
script: make test
