dist: trusty
language: python
python:
  - "3.5"
# command to install dependencies
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.5"
services:
  - redis-server
# for codecoverage on codeclimate.com
env:
  CODECLIMATE_REPO_TOKEN: 487c91389b4ddd1ea050bef2a1c822db7d54f302aad677daa82cd7ae92adfeb6
  CC_TEST_REPORTER_ID: 487c91389b4ddd1ea050bef2a1c822db7d54f302aad677daa82cd7ae92adfeb6
# command to run tests
script: make travis-test
