dist: trusty
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
addons:
  postgresql: "9.5"
# command to run tests
script: make travis-test
