# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamraemdISLResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_se', models.CharField(max_length=4)),
                ('mn_se', models.CharField(max_length=4)),
                ('ri_se', models.CharField(max_length=4)),
                ('se', models.CharField(max_length=4)),
                ('le_re', models.CharField(max_length=4)),
                ('mn_re', models.CharField(max_length=4)),
                ('ri_re', models.CharField(max_length=4)),
                ('re', models.CharField(max_length=4)),
                ('le_sg', models.CharField(max_length=4)),
                ('mn_sg', models.CharField(max_length=4)),
                ('ri_sg', models.CharField(max_length=4)),
                ('sg', models.CharField(max_length=4)),
                ('fm_fl', models.CharField(blank=True, max_length=32)),
                ('fm_txt', models.CharField(blank=True, max_length=256)),
                ('exam_code', models.CharField(max_length=256)),
                ('exam_date', models.DateField()),
                ('student_year', models.CharField(choices=[('1', '1. bekkur'), ('2', '2. bekkur'), ('3', '3. bekkur'), ('4', '4. bekkur'), ('5', '5. bekkur'), ('6', '6. bekkur'), ('7', '7. bekkur'), ('8', '8. bekkur'), ('9', '9. bekkur'), ('10', '10. bekkur')], max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SamraemdMathResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_se', models.CharField(max_length=4)),
                ('rm_se', models.CharField(max_length=4)),
                ('tt_se', models.CharField(max_length=4)),
                ('se', models.CharField(max_length=4)),
                ('ra_re', models.CharField(max_length=4)),
                ('rm_re', models.CharField(max_length=4)),
                ('tt_re', models.CharField(max_length=4)),
                ('re', models.CharField(max_length=4)),
                ('ra_sg', models.CharField(max_length=4)),
                ('rm_sg', models.CharField(max_length=4)),
                ('tt_sg', models.CharField(max_length=4)),
                ('sg', models.CharField(max_length=4)),
                ('ord_talna_txt', models.CharField(max_length=128)),
                ('fm_fl', models.CharField(blank=True, max_length=32)),
                ('fm_txt', models.CharField(blank=True, max_length=256)),
                ('exam_code', models.CharField(max_length=128)),
                ('exam_date', models.DateField()),
                ('student_year', models.CharField(choices=[('1', '1. bekkur'), ('2', '2. bekkur'), ('3', '3. bekkur'), ('4', '4. bekkur'), ('5', '5. bekkur'), ('6', '6. bekkur'), ('7', '7. bekkur'), ('8', '8. bekkur'), ('9', '9. bekkur'), ('10', '10. bekkur')], max_length=2)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SamraemdResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_code', models.CharField(choices=[(1, 'Íslenska'), (2, 'Enska'), (3, 'Stærðfræði')], max_length=2, null=True)),
                ('exam_name', models.CharField(max_length=125, null=True)),
                ('exam_date', models.DateField(default=django.utils.timezone.now)),
                ('student_year', models.CharField(choices=[('1', '1. bekkur'), ('2', '2. bekkur'), ('3', '3. bekkur'), ('4', '4. bekkur'), ('5', '5. bekkur'), ('6', '6. bekkur'), ('7', '7. bekkur'), ('8', '8. bekkur'), ('9', '9. bekkur'), ('10', '10. bekkur')], max_length=2, null=True)),
                ('result_data', jsonfield.fields.JSONField()),
                ('result_length', models.CharField(max_length=4)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
    ]
