# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samraemd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samraemdresult',
            name='ra_re',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='ra_se',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='ra_sg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='re',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='rm_re',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='rm_se',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='rm_sg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='se',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='sg',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='tt_re',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='tt_se',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='samraemdresult',
            name='tt_sg',
            field=models.IntegerField(),
        ),
    ]
