# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0034_auto_20160926_0916'),
        ('samraemd', '0002_auto_20161005_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='SamraemdISLResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('le_se', models.IntegerField()),
                ('mn_se', models.IntegerField()),
                ('ri_se', models.IntegerField()),
                ('se', models.IntegerField()),
                ('le_re', models.IntegerField()),
                ('mn_re', models.IntegerField()),
                ('ri_re', models.IntegerField()),
                ('re', models.IntegerField()),
                ('le_sg', models.IntegerField()),
                ('mn_sg', models.IntegerField()),
                ('ri_sg', models.IntegerField()),
                ('sg', models.IntegerField()),
                ('exam_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SamraemdMathResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ra_se', models.IntegerField()),
                ('rm_se', models.IntegerField()),
                ('tt_se', models.IntegerField()),
                ('se', models.IntegerField()),
                ('ra_re', models.IntegerField()),
                ('rm_re', models.IntegerField()),
                ('tt_re', models.IntegerField()),
                ('re', models.IntegerField()),
                ('ra_sg', models.IntegerField()),
                ('rm_sg', models.IntegerField()),
                ('tt_sg', models.IntegerField()),
                ('sg', models.IntegerField()),
                ('ord_talna_txt', models.CharField(max_length=128)),
                ('exam_date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.RemoveField(
            model_name='samraemdresult',
            name='student',
        ),
        migrations.DeleteModel(
            name='SamraemdResult',
        ),
    ]
