# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samraemd', '0004_auto_20161005_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='samraemdislresult',
            name='fm_fl',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samraemdislresult',
            name='fm_txt',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='samraemdmathresult',
            name='fm_fl',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samraemdmathresult',
            name='fm_txt',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='exam_code',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='le_se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='mn_se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='ri_se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='ra_se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='rm_se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='se',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='tt_se',
            field=models.CharField(max_length=4),
        ),
    ]
