# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-06 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samraemd', '0005_auto_20161006_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samraemdislresult',
            name='fm_fl',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='le_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='le_sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='mn_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='mn_sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='ri_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='ri_sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdislresult',
            name='sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='fm_fl',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='ra_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='ra_sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='rm_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='rm_sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='sg',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='tt_re',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='samraemdmathresult',
            name='tt_sg',
            field=models.CharField(max_length=4),
        ),
    ]
