# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-10-07 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samraemd', '0006_auto_20161006_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='samraemdislresult',
            name='student_year',
            field=models.CharField(choices=[('1', '1. bekkur'), ('2', '2. bekkur'), ('3', '3. bekkur'), ('4', '4. bekkur'), ('5', '5. bekkur'), ('6', '6. bekkur'), ('7', '7. bekkur'), ('8', '8. bekkur'), ('9', '9. bekkur'), ('10', '10. bekkur')], default='1', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='samraemdmathresult',
            name='student_year',
            field=models.CharField(choices=[('1', '1. bekkur'), ('2', '2. bekkur'), ('3', '3. bekkur'), ('4', '4. bekkur'), ('5', '5. bekkur'), ('6', '6. bekkur'), ('7', '7. bekkur'), ('8', '8. bekkur'), ('9', '9. bekkur'), ('10', '10. bekkur')], default='1', max_length=2),
            preserve_default=False,
        ),
    ]
