# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_security', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.RenameModel(
            old_name='StudentClass',
            new_name='StudentGroup',
        ),
        migrations.RenameField(
            model_name='studentgroup',
            old_name='class_name',
            new_name='group_name',
        ),
    ]
