# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20160411_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='social_security',
            new_name='ssn',
        ),
        migrations.RenameField(
            model_name='school',
            old_name='social_security',
            new_name='ssn',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='social_security',
            new_name='ssn',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='social_security',
            new_name='ssn',
        ),
    ]
