# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20160411_1340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.AddField(
            model_name='student',
            name='student_groups',
            field=models.ManyToManyField(to='common.StudentGroup'),
        ),
    ]
