# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20160411_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentgroup',
            old_name='group_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student_year',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
