# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_auto_20160411_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_groups',
            field=models.ManyToManyField(blank=True, null=True, to='common.StudentGroup'),
        ),
    ]
