# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_auto_20160414_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
