# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_auto_20160414_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='ssn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='ssn',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ssn',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
