# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-15 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_auto_20160414_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_groups',
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='students',
            field=models.ManyToManyField(blank=True, to='common.Student'),
        ),
    ]
