# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0017_auto_20160418_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=1024)),
                ('title', models.CharField(max_length=256)),
                ('active_from', models.DateField(default=django.utils.timezone.now)),
                ('active_to', models.DateField(default=django.utils.timezone.now)),
                ('studentgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.StudentGroup')),
            ],
        ),
    ]
