# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0018_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresult',
            name='data_fields',
            field=models.TextField(default='{}'),
            preserve_default=False,
        ),
    ]
