# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-22 15:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0020_auto_20160422_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyresult',
            name='completed_at',
        ),
    ]
