# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_auto_20160427_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='surveyresult',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Survey'),
        ),
    ]
