# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-22 09:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0025_surveylogin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='data_fields',
        ),
    ]
