# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-04 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0026_remove_survey_data_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='manager',
            name='email',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='manager',
            name='phone',
            field=models.CharField(blank=True, max_length=7),
        ),
    ]
