# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-23 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0028_notification'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set([('notification_type', 'notification_id')]),
        ),
    ]
