# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-07 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_auto_20160823_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='identifier',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
