# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0031_auto_20160908_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='position',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
