# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0032_manager_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='position',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
