# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0033_teacher_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresult',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
