# -*- coding: utf-8 -*-

STUDENT_YEAR_LIST = (
    ('0', 'Blandaður árgangur'),
    ('1', '1. bekkur'),
    ('2', '2. bekkur'),
    ('3', '3. bekkur'),
    ('4', '4. bekkur'),
    ('5', '5. bekkur'),
    ('6', '6. bekkur'),
    ('7', '7. bekkur'),
    ('8', '8. bekkur'),
    ('9', '9. bekkur'),
    ('10', '10. bekkur'),
)

POST_CODE_LIST = (
    ('101', '101'), ('103', '103'), ('104', '104'), ('105', '105'), ('107', '107'), ('108', '108'), ('109', '109'),
    ('110', '110'), ('111', '111'), ('112', '112'), ('113', '113'), ('116', '116'), ('121', '121'), ('123', '123'),
    ('124', '124'), ('125', '125'), ('127', '127'), ('128', '128'), ('129', '129'), ('130', '130'), ('132', '132'),
    ('170', '170'), ('172', '172'), ('190', '190'), ('200', '200'), ('201', '201'), ('202', '202'), ('203', '203'),
    ('210', '210'), ('212', '212'), ('220', '220'), ('221', '221'), ('222', '222'), ('225', '225'), ('230', '230'),
    ('232', '232'), ('233', '233'), ('235', '235'), ('240', '240'), ('245', '245'), ('250', '250'), ('260', '260'),
    ('270', '270'), ('271', '271'), ('276', '276'), ('300', '300'), ('301', '301'), ('302', '302'), ('310', '310'),
    ('311', '311'), ('320', '320'), ('340', '340'), ('345', '345'), ('350', '350'), ('355', '355'), ('356', '356'),
    ('360', '360'), ('370', '370'), ('371', '371'), ('380', '380'), ('400', '400'), ('401', '401'), ('410', '410'),
    ('415', '415'), ('420', '420'), ('425', '425'), ('430', '430'), ('450', '450'), ('451', '451'), ('460', '460'),
    ('465', '465'), ('470', '470'), ('471', '471'), ('500', '500'), ('510', '510'), ('512', '512'), ('520', '520'),
    ('524', '524'), ('530', '530'), ('531', '531'), ('540', '540'), ('541', '541'), ('545', '545'), ('550', '550'),
    ('551', '551'), ('560', '560'), ('565', '565'), ('566', '566'), ('570', '570'), ('580', '580'), ('600', '600'),
    ('601', '601'), ('602', '602'), ('603', '603'), ('610', '610'), ('611', '611'), ('620', '620'), ('621', '621'),
    ('625', '625'), ('630', '630'), ('640', '640'), ('641', '641'), ('645', '645'), ('650', '650'), ('660', '660'),
    ('670', '670'), ('671', '671'), ('675', '675'), ('680', '680'), ('681', '681'), ('685', '685'), ('690', '690'),
    ('700', '700'), ('701', '701'), ('710', '710'), ('715', '715'), ('720', '720'), ('730', '730'), ('735', '735'),
    ('740', '740'), ('750', '750'), ('755', '755'), ('760', '760'), ('765', '765'), ('780', '780'), ('781', '781'),
    ('785', '785'), ('800', '800'), ('801', '801'), ('802', '802'), ('810', '810'), ('815', '815'), ('816', '816'),
    ('820', '820'), ('825', '825'), ('840', '840'), ('845', '845'), ('850', '850'), ('851', '851'), ('860', '860'),
    ('861', '861'), ('870', '870'), ('871', '871'), ('880', '880'), ('900', '900'), ('902', '902'),
)

MUNICIPALITIES_LIST = (
    ('Hafnarfjarðarkaupstaður', 'Hafnarfjarðarkaupstaður'),
    ('Reykjanesbær', 'Reykjanesbær'),
    ('Garðabær', 'Garðabær'),
    ('Dalabyggð', 'Dalabyggð'),
    ('Reykjavíkurborg', 'Reykjavíkurborg'),
    ('Kópavogsbær', 'Kópavogsbær'),
    ('Dalvíkurbyggð', 'Dalvíkurbyggð'),
    ('Sveitarf. Skagafjörður', 'Sveitarf. Skagafjörður'),
    ('Sveitarfélagið Árborg', 'Sveitarfélagið Árborg'),
    ('Bláskógabyggð', 'Bláskógabyggð'),
    ('Blönduósbær', 'Blönduósbær'),
    ('Norðurþing', 'Norðurþing'),
    ('Akraneskaupstaður', 'Akraneskaupstaður'),
    ('Akureyrarkaupstaður', 'Akureyrarkaupstaður'),
    ('Fljótsdalshérað', 'Fljótsdalshérað'),
    ('Árneshreppur', 'Árneshreppur'),
    ('Flóahreppi', 'Flóahreppi'),
    ('Hrunamannahreppur', 'Hrunamannahreppur'),
    ('Sveitarfélagið Garður', 'Sveitarfélagið Garður'),
    ('Grýtubakkahreppur', 'Grýtubakkahreppur'),
    ('Bolungarvíkurkaupstaður', 'Bolungarvíkurkaupstaður'),
    ('Borgarbyggð', 'Borgarbyggð'),
    ('Borgarfjarðarhreppur', 'Borgarfjarðarhreppur'),
    ('Djúpavogshreppur', 'Djúpavogshreppur'),
    ('Fjarðabyggð', 'Fjarðabyggð'),
    ('Fjallabyggð', 'Fjallabyggð'),
    ('Grindavíkurbær', 'Grindavíkurbær'),
    ('Grundarfjarðarbær', 'Grundarfjarðarbær'),
    ('Sveitarfélagið Hornafjörður', 'Sveitarfélagið Hornafjörður'),
    ('Bæjarhreppur', 'Bæjarhreppur'),
    ('Húnaþing vestra', 'Húnaþing vestra'),
    ('Seltjarnarnesbær', 'Seltjarnarnesbær'),
    ('Snæfellsbær', 'Snæfellsbær'),
    ('Vestmannaeyjabær', 'Vestmannaeyjabær'),
    ('Vesturbyggð', 'Vesturbyggð'),
    ('Ísafjarðarbær', 'Ísafjarðarbær'),
    ('Langanesbyggð', 'Langanesbyggð'),
    ('Kaldrananeshreppur', 'Kaldrananeshreppur'),
    ('Strandabyggð', 'Strandabyggð'),
    ('Tálknafjarðarhreppur', 'Tálknafjarðarhreppur'),
    ('Rangárþing ytra', 'Rangárþing ytra'),
    ('Breiðdalshreppur', 'Breiðdalshreppur'),
    ('Hveragerðisbær', 'Hveragerðisbær'),
    ('Sandgerðisbær', 'Sandgerðisbær'),
    ('Stykkishólmsbær', 'Stykkishólmsbær'),
    ('Sveitarfélagið Ölfus', 'Sveitarfélagið Ölfus'),
    ('Hvalfjarðarsveit', 'Hvalfjarðarsveit'),
    ('Eyjafjarðarsveit', 'Eyjafjarðarsveit'),
    ('Húnavatnshreppi', 'Húnavatnshreppi'),
    ('Rangárþing eystra', 'Rangárþing eystra'),
    ('Sveitarf. Skagaströnd', 'Sveitarf. Skagaströnd'),
    ('Grímsnes- og Grafningshreppur', 'Grímsnes- og Grafningshreppur'),
    ('Skaftárhreppur', 'Skaftárhreppur'),
    ('Mosfellsbær', 'Mosfellsbær'),
    ('Rangárþingi ytra', 'Rangárþingi ytra'),
    ('Eyja-og Miklaholtshreppur', 'Eyja-og Miklaholtshreppur'),
    ('Reykhólahreppur', 'Reykhólahreppur'),
    ('Skútustaðahreppur', 'Skútustaðahreppur'),
    ('Seyðisfjarðarkaupstaður', 'Seyðisfjarðarkaupstaður'),
    ('Þingeyjarsveit', 'Þingeyjarsveit'),
    ('Sveitarfélagið Vogar', 'Sveitarfélagið Vogar'),
    ('Súðavikurhreppur', 'Súðavikurhreppur'),
    ('Svalbarðsstrandarhreppur', 'Svalbarðsstrandarhreppur'),
    ('Mýrdalshreppur', 'Mýrdalshreppur'),
    ('Vopnafjarðarhreppur', 'Vopnafjarðarhreppur'),
    ('Hörgársveit', 'Hörgársveit'),
    ('Skeiða- og Gnúpverjahreppi', 'Skeiða- og Gnúpverjahreppi'),
    ('Hafnarfjarðarkaupstaður', 'Hafnarfjarðarkaupstaður'),
    ('Reykjanesbær', 'Reykjanesbær'),
    ('Garðabær', 'Garðabær'),
    ('Dalabyggð', 'Dalabyggð'),
    ('Reykjavíkurborg', 'Reykjavíkurborg'),
    ('Kópavogsbær', 'Kópavogsbær'),
    ('Dalvíkurbyggð', 'Dalvíkurbyggð'),
    ('Sveitarf. Skagafjörður', 'Sveitarf. Skagafjörður'),
    ('Sveitarfélagið Árborg', 'Sveitarfélagið Árborg'),
    ('Bláskógabyggð', 'Bláskógabyggð'),
    ('Blönduósbær', 'Blönduósbær'),
    ('Norðurþing', 'Norðurþing'),
    ('Akraneskaupstaður', 'Akraneskaupstaður'),
    ('Akureyrarkaupstaður', 'Akureyrarkaupstaður'),
    ('Fljótsdalshérað', 'Fljótsdalshérað'),
    ('Árneshreppur', 'Árneshreppur'),
    ('Flóahreppi', 'Flóahreppi'),
    ('Hrunamannahreppur', 'Hrunamannahreppur'),
    ('Sveitarfélagið Garður', 'Sveitarfélagið Garður'),
    ('Grýtubakkahreppur', 'Grýtubakkahreppur'),
    ('Bolungarvíkurkaupstaður', 'Bolungarvíkurkaupstaður'),
    ('Borgarbyggð', 'Borgarbyggð'),
    ('Borgarfjarðarhreppur', 'Borgarfjarðarhreppur'),
    ('Djúpavogshreppur', 'Djúpavogshreppur'),
    ('Fjarðabyggð', 'Fjarðabyggð'),
    ('Fjallabyggð', 'Fjallabyggð'),
    ('Grindavíkurbær', 'Grindavíkurbær'),
    ('Grundarfjarðarbær', 'Grundarfjarðarbær'),
    ('Sveitarfélagið Hornafjörður', 'Sveitarfélagið Hornafjörður'),
    ('Bæjarhreppur', 'Bæjarhreppur'),
    ('Húnaþing vestra', 'Húnaþing vestra'),
    ('Seltjarnarnesbær', 'Seltjarnarnesbær'),
    ('Snæfellsbær', 'Snæfellsbær'),
    ('Vestmannaeyjabær', 'Vestmannaeyjabær'),
    ('Vesturbyggð', 'Vesturbyggð'),
    ('Ísafjarðarbær', 'Ísafjarðarbær'),
    ('Langanesbyggð', 'Langanesbyggð'),
    ('Kaldrananeshreppur', 'Kaldrananeshreppur'),
    ('Strandabyggð', 'Strandabyggð'),
    ('Tálknafjarðarhreppur', 'Tálknafjarðarhreppur'),
    ('Rangárþing ytra', 'Rangárþing ytra'),
    ('Breiðdalshreppur', 'Breiðdalshreppur'),
    ('Hveragerðisbær', 'Hveragerðisbær'),
    ('Sandgerðisbær', 'Sandgerðisbær'),
    ('Stykkishólmsbær', 'Stykkishólmsbær'),
    ('Sveitarfélagið Ölfus', 'Sveitarfélagið Ölfus'),
    ('Hvalfjarðarsveit', 'Hvalfjarðarsveit'),
    ('Eyjafjarðarsveit', 'Eyjafjarðarsveit'),
    ('Húnavatnshreppi', 'Húnavatnshreppi'),
    ('Rangárþing eystra', 'Rangárþing eystra'),
    ('Sveitarf. Skagaströnd', 'Sveitarf. Skagaströnd'),
    ('Grímsnes- og Grafningshreppur', 'Grímsnes- og Grafningshreppur'),
    ('Skaftárhreppur', 'Skaftárhreppur'),
    ('Mosfellsbær', 'Mosfellsbær'),
    ('Rangárþingi ytra', 'Rangárþingi ytra'),
    ('Eyja-og Miklaholtshreppur', 'Eyja-og Miklaholtshreppur'),
    ('Reykhólahreppur', 'Reykhólahreppur'),
    ('Skútustaðahreppur', 'Skútustaðahreppur'),
    ('Seyðisfjarðarkaupstaður', 'Seyðisfjarðarkaupstaður'),
    ('Þingeyjarsveit', 'Þingeyjarsveit'),
    ('Sveitarfélagið Vogar', 'Sveitarfélagið Vogar'),
    ('Súðavikurhreppur', 'Súðavikurhreppur'),
    ('Svalbarðsstrandarhreppur', 'Svalbarðsstrandarhreppur'),
    ('Mýrdalshreppur', 'Mýrdalshreppur'),
    ('Vopnafjarðarhreppur', 'Vopnafjarðarhreppur'),
    ('Hörgársveit', 'Hörgársveit'),
    ('Skeiða- og Gnúpverjahreppi', 'Skeiða- og Gnúpverjahreppi'),
)

COUNTRY_PARTS_LIST = (
    ('Ngr. Reykjavíkur', 'Ngr. Reykjavíkur'),
    ('Suðurnes', 'Suðurnes'),
    ('Vesturland', 'Vesturland'),
    ('Reykjavík', 'Reykjavík'),
    ('Norðurland eystra', 'Norðurland eystra'),
    ('Norðurland vestra', 'Norðurland vestra'),
    ('Suðurland', 'Suðurland'),
    ('Austurland', 'Austurland'),
    ('Vestfirðir', 'Vestfirðir'),
)
