# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1)),
                ('exam', models.CharField(max_length=32)),
                ('explanation', models.CharField(max_length=1024)),
                ('exceptionsdate', models.DateField(auto_now_add=True, null=True)),
                ('exceptionssignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Manager')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExceptionSupport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(max_length=500)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
            ],
        ),
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=1024)),
                ('supportresourcedate', models.DateField(auto_now=True, null=True)),
                ('support_title', models.CharField(max_length=32, null=True)),
                ('reading_assistance', models.CharField(max_length=32, null=True)),
                ('interpretation', models.CharField(max_length=32, null=True)),
                ('longer_time', models.CharField(max_length=32, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Student')),
                ('supportresourcesignature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Manager')),
            ],
        ),
    ]
