# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-26 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exceptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=1)),
                ('exam', models.CharField(max_length=1)),
                ('explanation', models.CharField(max_length=500)),
                ('signature', models.CharField(max_length=140)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialsecurity', models.CharField(max_length=140)),
                ('name', models.CharField(max_length=140)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyear', models.CharField(max_length=140)),
                ('stuclass', models.CharField(max_length=140)),
                ('school', models.CharField(max_length=140)),
                ('year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SupportResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.CharField(max_length=500)),
                ('signature', models.CharField(max_length=140)),
                ('date', models.DateField(auto_now=True, null=True)),
                ('support_title', models.CharField(max_length=1, null=True)),
                ('reading_assistance', models.CharField(max_length=1, null=True)),
                ('interpretation', models.CharField(max_length=1, null=True)),
                ('return_to_sites', models.CharField(max_length=1, null=True)),
                ('longer_time', models.CharField(max_length=1, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportandexception.Student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supportandexception.StudentClass'),
        ),
        migrations.AddField(
            model_name='exceptions',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supportandexception.Student'),
        ),
    ]
