# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-25 10:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supportandexception', '0005_remove_supportresource_return_to_sites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceptions',
            old_name='date',
            new_name='exceptionsdate',
        ),
        migrations.RenameField(
            model_name='exceptions',
            old_name='signature',
            new_name='exceptionssignature',
        ),
        migrations.RenameField(
            model_name='supportresource',
            old_name='date',
            new_name='supportresourcedate',
        ),
        migrations.RenameField(
            model_name='supportresource',
            old_name='signature',
            new_name='supportresourcesignature',
        ),
    ]
