# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-21 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supportandexception', '0006_auto_20160725_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceptions',
            name='exceptionssignature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Manager'),
        ),
        migrations.AlterField(
            model_name='supportresource',
            name='supportresourcesignature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Manager'),
        ),
    ]
